administer/administer/funcionarios/models.py
from administer import db

class Funcionario(db.Model):
	"""docstring for Funcionario"""

	__tablename__ = "funcionarios"

	id = db.Column(db.Integer, primary_key=True)
	nome = db.Column(db.String(120), nullable=False)
	idade = db.Column(db.Integer, nullable=False)
	email = db.Column(db.String(120), nullable=False)
	setor = db.Column(db.String(120), nullable=False)

	admin_id = db.Column(db.Integer, db.ForeignKey('administradores.id'))
	
	def __init__(self, form):
		self.nome = form.nome.data     # self.nome = nome
		self.idade = form.idade.data   # self.idade = idade 
		self.email = form.email.data   # self.email = email  
		self.setor = form.setor.data   # self.setor = setor 

administer/administer/funcionarios/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField, BooleanField, SelectField,
					 TextAreaField, RadioField, IntegerField)
from wtforms.validators import DataRequired, Length, Email


class funcionario_form(FlaskForm ):
	
	nome = StringField("Nome", validators=[DataRequired(message="Esse campo é obrigatório"), Length(min=3, max=120, message="Tamanho mínimo de 3 caracteres e maxímo de 120!")])
	idade = IntegerField("Idade", validators=[DataRequired(message="Esse campo é obrigatório")])
	email = StringField("Email", validators=[DataRequired(message="Esse campo é obrigatório"), Length(min=3, max=120, message="Tamanho mínimo de 3 caracteres e maxímo de 120!"), Email()])
	setor = SelectField("Setor", validators=[DataRequired(message="Esse campo é obrigatório")], choices=[("0", "Equipe administrativo"), ("1", "Desenvolvedor"), ("2", "Equipe projetos"), ("3", "Equipe RH"), ("4", "Equipe marketing"), ("5", "Equipe presidencia"), ("6", "Equipe Negocios")])
	submit = SubmitField("Novo Funcionário")

administer/administer/funcionarios/views.py
from flask import (render_template, request, Blueprint, url_for, redirect, request, flash, abort,
					make_response, jsonify)
from administer.funcionarios.forms import funcionario_form
from administer.funcionarios.models import Funcionario
from flask_login import LoginManager, current_user
from administer import login_required, db

funcionarios = Blueprint('funcionarios', __name__, template_folder='templates')

def valida_formulario(data):

	if (len(data["nome"]) <= 3 or len(data["nome"]) >= 120):
		return False


	try:

		len_email1 = len(data["email"].split("@"))
		len_email2 = len(data["email"].split("@")[-1].split('.'))

		if (len_email1 <= 0 or len_email1 > 2):
			return False
		if (len_email2 <= 0):
			return False

		if (int(data["idade"]) < 14 or int(data["idade"]) >= 180):
			return False

		if (int(data["setor"]) > 6 or int(data["setor"]) < 0):
			return False

	except:

		return False

	return True



@login_required()
@funcionarios.route("/adicionar", methods=["POST", "GET"])
def adicionar():
	
	add_funcionario = funcionario_form()
	
	if add_funcionario.validate_on_submit():
		print("Errado, to aqui")

		new_employer = Funcionario(add_funcionario)

		new_employer.admin_id = current_user.id

		db.session.add(new_employer)
		db.session.commit()
		flash("Adicionado", "danger")
		
		return redirect(url_for('funcionarios.exibe_all'))

	
	flash("Deu Ruim", "danger")

	return redirect(url_for('usuarios.dashboard'))


@login_required()
@funcionarios.route("/excluir/<int:id>", methods=["POST", "GET"])
def excluir(id):
	
	del_employer = Funcionario.query.get_or_404(id)

	if del_employer.admin.id != current_user.id:
		abort(403)

	db.session.delete(del_employer)
	db.session.commit()

	return redirect(url_for('funcionarios.meus_funcionarios'))

@login_required()
@funcionarios.route("/editar/<int:id>", methods=["POST", "GET"])
def editar(id):
	
	edit_employer = Funcionario.query.get_or_404(id)

	if edit_employer.admin.id != current_user.id:

		res = make_response(jsonify({"message": "Aqui não FDP"}), 403)
		return res

	data = request.get_json()

	edit_employer.nome = data["nome"]
	edit_employer.idade = data["idade"]
	edit_employer.email = data["email"]
	edit_employer.setor = data["setor"]

	res = make_response(jsonify({"message": "JSON recebido"}), 200)

	if not valida_formulario(data):
		
		res = make_response(jsonify({"message": "JSON crashado"}), 500)
		return res

	db.session.commit()

	return res

@login_required()
@funcionarios.route("/exibe_all")
def exibe_all():
	add_funcionario = funcionario_form()

	titulo = "Todos funcionários"
	setor = [("0", "Equipe administrativo"), ("1", "Desenvolvedor"), ("2", "Equipe projetos"), ("3", "Equipe RH"), ("4", "Equipe marketing"), ("5", "Equipe presidencia"), ("6", "Equipe Negocios")]
	setor = dict(setor)

	page = request.args.get('page', 1, type=int)
	funcionarios = Funcionario.query.paginate(page=page, per_page=12)
	return render_template("todos_funcionarios.html", setor=setor, titulo=titulo, funcionarios=funcionarios, add_funcionario=add_funcionario)

@login_required()
@funcionarios.route("/meus_funcionarios")
def meus_funcionarios():
	add_funcionario = funcionario_form()

	titulo = "Meus funcionários"
	setor = [("0", "Equipe administrativo"), ("1", "Desenvolvedor"), ("2", "Equipe projetos"), ("3", "Equipe RH"), ("4", "Equipe marketing"), ("5", "Equipe presidencia"), ("6", "Equipe Negocios")]
	setor = dict(setor)

	page = request.args.get('page', 1, type=int)
	funcionarios = Funcionario.query.filter_by(admin_id=current_user.id).paginate(page=page, per_page=12)
	
	return render_template("todos_funcionarios.html", setor=setor, titulo=titulo, funcionarios=funcionarios, add_funcionario=add_funcionario)

@login_required()
@funcionarios.route("/exibe/<int:id>")
def exibe(id):
	
	add_funcionario = funcionario_form()
	funcionario = Funcionario.query.get_or_404(id)

	return render_template("funcionario.html", add_funcionario=add_funcionario, funcionario=funcionario)

@login_required()
@funcionarios.route("/busca/<string:nome>", methods=["GET"])
def busca(nome):

	setor = [("0", "Equipe administrativo"), ("1", "Desenvolvedor"), ("2", "Equipe projetos"), ("3", "Equipe RH"), ("4", "Equipe marketing"), ("5", "Equipe presidencia"), ("6", "Equipe Negocios")]
	setor = dict(setor)

	page = request.args.get('page', 1, type=int)
	funcionarios = Funcionario.query.filter_by(nome=nome).paginate(page=page, per_page=12)
	return render_template("busca_funcionario.html", setor=setor, funcionarios=funcionarios)


	

administer/administer/funcionarios/templates/busca_funcionario.html
{% for employer in funcionarios.items %}
<div>
    <style>
      .demo-card-square.mdl-card {
        width: 320px;
        height: 320px;
        margin: 10px;
      }
      .demo-card-square > .mdl-card__title {
        color: #fff;
        background:
          url('../assets/demos/dog.png') bottom right 15% no-repeat #46B6AC;
      }
      </style>
      
      <div class="demo-card-square mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand">
          <h2 class="mdl-card__title-text">{{employer.nome}}</h2>
        </div>
        <div class="mdl-card__supporting-text">
          {{ setor[employer.setor] }}
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="{{ url_for('funcionarios.exibe', id=employer.id) }}">
            Mais Informações
          </a>
        </div>
      </div>
    </div>
  {% endfor %}

{% endblock %}


{%  block pagination %}
<br/>
  <div style="size: 100%;" class="text-center">
    <div class="ui pagination menu">
      {% for page_num in funcionarios.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if funcionarios.page == page_num and page_num %}
            <a class="disabled item">
              {{ page_num }}
            </a>
          {% elif page_num %}
            <a class="active item" href="{{ url_for('funcionarios.exibe_all', page=page_num) }}">
              {{ page_num }}
            </a>
          {% else %}
            <div class="disabled item">
              ...
            </div>
          {% endif %}
      {% endfor %}
    </div>
  </div>
<br/>
  
{% endblock %}

            

administer/administer/funcionarios/templates/funcionario.html
{% extends "base.html"%}

{%block title%} Consulta  {% endblock %}

{% block content %}

     

<!-- Default form subscription -->
<form class="form-control">

    {% if funcionario.admin.id == current_user.id %}

        <p class="h4 mb-4">Editar funcionário</p>
        <p>Trocar informações sobre os funcionários</p>

    {% else %}

        <p class="h4 mb-3">Informações do funcionário</p>
        <p>Simples consulta</p>

        <p class="h4 mb-4">Cadastrado por: {{ funcionario.admin.nome }}</p>

    {% endif %}
    <hr/>


   <!-- Name -->
    <input id="nome_edit" type="text" class="form-control form-control-lg mb-4" placeholder="Name" value="{{funcionario.nome}}">

    <!-- Email -->
    <input id="email_edit" type="email" class="form-control form-control-lg mb-4" placeholder="E-mail" value="{{funcionario.email}}">

    <!-- Idade -->
    <input id="idade_edit" type="text" class="form-control form-control-lg mb-4" placeholder="Idade" value="{{funcionario.idade}}">

    <select id="setor_edit" class="browser-default custom-select custom-select-lg">
      <option value="0">Equipe de Administração Financeira</option>
      <option value="1">Desenvolvedor</option>
      <option value="2">Equipe de Projetos</option>
      <option value="3">Equipe de RH</option>
      <option value="4">Equipe de Marketing</option>
      <option value="5">Presidência</option>
      <option value="6">Equipe de Negócios</option>    
    </select>

    <!-- Sign in button -->
    <br/>
    <br/>
    <br/>
    {% if funcionario.admin.id == current_user.id %}

        <btn class="btn btn-info" onclick="atualiza()">Alterar</btn>
        <a class="btn btn-danger" href="{{url_for('funcionarios.excluir', id=funcionario.id)}}" >Deletar</a>

    {% endif %}

</form>
<!-- Default form subscription -->
     
{% if funcionario.admin.id == current_user.id %}

{%  block script %}

<script type="text/javascript">
    
    function atualiza(){
        
        let nome = $("#nome_edit").val();
        let email = $("#email_edit").val();
        let idade = $("#idade_edit").val();
        let setor = $("#setor_edit").val();

        var update = {
            nome: nome,
            email: email,
            idade: idade,
            setor: setor
        };

        console.log(update)

        fetch(window.origin + '/funcionarios/editar/{{funcionario.id}}', {
            
            method: "POST",
            credentials: "include", //Pega as informações em coock e coloca na requisição
            body: JSON.stringify(update),
            cache: "no-cache",
            headers: new Headers({
                "content-type": "application/json"
            })

        }).then(function (response){

            if(response.status !== 200){
                console.log("Response status foi boicotado: " + response.status);
                return ;
            }

            response.json().then(function (data){
                console.log(data)
            })
        })

    }

</script>

{% endblock %}

{% endif %}

{% endblock %}

administer/administer/funcionarios/templates/todos_funcionarios.html
{% extends "base.html"%}

{%block title%} {{titulo}} {% endblock %}

{% block content %}

<script>
  function busca(exibi ,endereco){

    $.ajax({type : 'GET', 
        url: endereco+"/"+$("#coisa_field").val(),
        success: function(result){
            $("#"+exibi).html(result)
        },
        complete: function(){
          alert(this.readyState)
        },
      })

  }
</script>

<div style="right: 0px;" class="mdl-textfield mdl-js-textfield">
  <input id="coisa_field" style="float: left" class="mdl-textfield__input" type="text" id="sample1" placeholder="Search">
  <button style="float: right" onclick="busca('resultado' ,'/busca');" type="submit" class="mdl-button mdl-js-button mdl-button--icon">Search
  </button>
</div>
{% for employer in funcionarios.items %}
<div style="display: block" id="div_todos_funcionarios">
<style>
  .demo-card-square.mdl-card {
    width: 320px;
    height: 320px;
    margin: 10px;
  }
  .demo-card-square > .mdl-card__title {
    color: #fff;
    background:
      url('../assets/demos/dog.png') bottom right 15% no-repeat #46B6AC;
  }
  </style>
  
  <div class="demo-card-square mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title mdl-card--expand">
      <h2 class="mdl-card__title-text">{{employer.nome}}</h2>
    </div>
    <div class="mdl-card__supporting-text">
      {{ setor[employer.setor] }}
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="{{ url_for('funcionarios.exibe', id=employer.id) }}">
        Mais Informações
      </a>
    </div>
  </div>
</div>
<div id="resultado">

</div>

{% endfor %}

{% endblock %}


{%  block pagination %}
<br/>
<div style="size: 100%;" class="text-center">
<div class="ui pagination menu">
  {% for page_num in funcionarios.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if funcionarios.page == page_num and page_num %}
        <a class="disabled item">
          {{ page_num }}
        </a>
      {% elif page_num %}
        <a class="active item" href="{{ url_for('funcionarios.exibe_all', page=page_num) }}">
          {{ page_num }}
        </a>
      {% else %}
        <div class="disabled item">
          ...
        </div>
      {% endif %}
  {% endfor %}
</div>
</div>
<br/>

{% endblock %}