administer/administer/funcionarios/views.py
from flask import (render_template, request, Blueprint, url_for, redirect, request, flash, abort,
					make_response, jsonify)
from administer.funcionarios.forms import funcionario_form
from administer.funcionarios.models import Funcionario
from flask_login import LoginManager, current_user
from administer import login_required, db

funcionarios = Blueprint('funcionarios', __name__, template_folder='templates')

def valida_formulario(data):

	if (len(data["nome"]) <= 3 or len(data["nome"]) >= 120):
		return False


	try:

		len_email1 = len(data["email"].split("@"))
		len_email2 = len(data["email"].split("@")[-1].split('.'))

		if (len_email1 <= 0 or len_email1 > 2):
			return False
		if (len_email2 <= 0):
			return False

		if (int(data["idade"]) < 14 or int(data["idade"]) >= 180):
			return False

		if (int(data["setor"]) > 6 or int(data["setor"]) < 0):
			return False

	except:

		return False

	return True



@login_required()
@funcionarios.route("/adicionar", methods=["POST", "GET"])
def adicionar():
	
	add_funcionario = funcionario_form()
	
	if add_funcionario.validate_on_submit():
		print("Errado, to aqui")

		new_employer = Funcionario(add_funcionario)

		new_employer.admin_id = current_user.id

		db.session.add(new_employer)
		db.session.commit()
		flash("Adicionado", "danger")
		
		return redirect(url_for('funcionarios.exibe_all'))

	
	flash("Deu Ruim", "danger")

	return redirect(url_for('usuarios.dashboard'))


@login_required()
@funcionarios.route("/excluir/<int:id>", methods=["POST", "GET"])
def excluir(id):
	
	del_employer = Funcionario.query.get_or_404(id)

	if del_employer.admin.id != current_user.id:
		abort(403)

	db.session.delete(del_employer)
	db.session.commit()

	return redirect(url_for('funcionarios.meus_funcionarios'))

@login_required()
@funcionarios.route("/editar/<int:id>", methods=["POST", "GET"])
def editar(id):
	
	edit_employer = Funcionario.query.get_or_404(id)

	if edit_employer.admin.id != current_user.id:

		res = make_response(jsonify({"message": "Aqui não FDP"}), 403)
		return res

	data = request.get_json()

	edit_employer.nome = data["nome"]
	edit_employer.idade = data["idade"]
	edit_employer.email = data["email"]
	edit_employer.setor = data["setor"]

	res = make_response(jsonify({"message": "JSON recebido"}), 200)

	if not valida_formulario(data):
		
		res = make_response(jsonify({"message": "JSON crashado"}), 500)
		return res

	db.session.commit()

	return res

@login_required()
@funcionarios.route("/exibe_all")
def exibe_all():
	add_funcionario = funcionario_form()

	titulo = "Todos funcionários"
	setor = [("0", "Equipe administrativo"), ("1", "Desenvolvedor"), ("2", "Equipe projetos"), ("3", "Equipe RH"), ("4", "Equipe marketing"), ("5", "Equipe presidencia"), ("6", "Equipe Negocios")]
	setor = dict(setor)

	page = request.args.get('page', 1, type=int)
	funcionarios = Funcionario.query.paginate(page=page, per_page=12)
	return render_template("todos_funcionarios.html", setor=setor, titulo=titulo, funcionarios=funcionarios, add_funcionario=add_funcionario)

@login_required()
@funcionarios.route("/meus_funcionarios")
def meus_funcionarios():
	add_funcionario = funcionario_form()

	titulo = "Meus funcionários"
	setor = [("0", "Equipe administrativo"), ("1", "Desenvolvedor"), ("2", "Equipe projetos"), ("3", "Equipe RH"), ("4", "Equipe marketing"), ("5", "Equipe presidencia"), ("6", "Equipe Negocios")]
	setor = dict(setor)

	page = request.args.get('page', 1, type=int)
	funcionarios = Funcionario.query.filter_by(admin_id=current_user.id).paginate(page=page, per_page=12)
	
	return render_template("todos_funcionarios.html", setor=setor, titulo=titulo, funcionarios=funcionarios, add_funcionario=add_funcionario)

@login_required()
@funcionarios.route("/exibe/<int:id>")
def exibe(id):
	
	add_funcionario = funcionario_form()
	funcionario = Funcionario.query.get_or_404(id)

	return render_template("funcionario.html", add_funcionario=add_funcionario, funcionario=funcionario)

@login_required()
@funcionarios.route("/busca/<string:nome>", methods=["GET"])
def busca(nome):

	setor = [("0", "Equipe administrativo"), ("1", "Desenvolvedor"), ("2", "Equipe projetos"), ("3", "Equipe RH"), ("4", "Equipe marketing"), ("5", "Equipe presidencia"), ("6", "Equipe Negocios")]
	setor = dict(setor)

	page = request.args.get('page', 1, type=int)
	funcionarios = Funcionario.query.filter_by(nome=nome).paginate(page=page, per_page=12)
	return render_template("busca_funcionario.html", setor=setor, funcionarios=funcionarios)


	

administer/administer/usuarios/views.py
from flask import (render_template, request, Blueprint, url_for, redirect, request, flash, abort)
from administer.usuarios.models import Admin
from administer.usuarios.forms import AdicionarUserForm, LoginForm, EditarUserForm
from flask_login import LoginManager, current_user, login_user, logout_user
from administer import login_required
from administer.usuarios.avatar import adicionar_avatar
from flask_bcrypt import Bcrypt
from administer import db
from administer.funcionarios.models import Funcionario
from administer.funcionarios.forms import funcionario_form

usuarios = Blueprint('usuarios', __name__,template_folder='templates/usuarios')

@usuarios.route("/dashboard", methods=["POST", "GET"])
@login_required()
def dashboard():
	totalSetor =[]
	add_funcionario = funcionario_form()

	funcionarios = Funcionario.query.filter_by(admin_id=current_user.id)
	for func in funcionarios:
		totalSetor.append(func.setor)
	
	tabela = [totalSetor.count('0'),totalSetor.count('1'),totalSetor.count('2'),totalSetor.count('3'),totalSetor.count('4'),totalSetor.count('5'),totalSetor.count('6')]

	return render_template("dashboard.html", add_funcionario=add_funcionario, tabela=tabela)

@usuarios.route('/cadastro', methods=['POST', 'GET'])
def adicionar():

	form_add = AdicionarUserForm(prefix="form_add")

	if form_add.validate_on_submit() and not Admin.query.filter_by(username=form_add.username.data).first() and not Admin.query.filter_by(email=form_add.email.data).first(): 
		bcript = Bcrypt()

		nome = form_add.nome.data
		username = form_add.username.data
		email = form_add.email.data
		data_nasc = form_add.data_nascimento.data

		hhash = bcript.generate_password_hash(form_add.senha.data)

		avatar = adicionar_avatar(form_add.foto.data, username) 
		
		novo_user = Admin(nome, email, username, data_nasc, hhash, avatar)
		print(novo_user)
		db.session.add(novo_user)
		db.session.commit()

		flash("Agradecemos o seu cadastro. Entre agora mesmo na sua conta e aproveite o Administer.", "success")

		return redirect(url_for('principal.index'))

	if Admin.query.filter_by(username=form_add.username.data).first():
		flash(f"Esse nome de usuário já existe.", "warning")

	if Admin.query.filter_by(email=form_add.email.data).first():
		flash(f"Esse e-mail já está em uso.", "warning")

	return redirect(url_for('principal.index'))

@usuarios.route('/login', methods=['POST', 'GET'])
def login():
	form_login = LoginForm(prefix="form_login")

	if form_login.validate_on_submit():
		user = Admin.query.filter_by(email=form_login.email.data).first()

		if user is not None:
			
			if user.check_password(form_login.senha.data):

				login_user(user, remember=form_login.lembrar.data)
				flash("Você foi logado com sucesso.", "success")
			
				return redirect(url_for('usuarios.dashboard'))

			else:
				flash("Email e/ou senha incorretos", "alert")
		else:
			flash("Email e/ou senha incorretos", "warning")

	return redirect(url_for('principal.index'))

@usuarios.route('/logout', methods=['POST', 'GET'])
@login_required()
def logout():
	logout_user()
	flash("Você foi deslogado com sucesso.", "success")
	return redirect(url_for('principal.index'))

@login_required()
@usuarios.route("/perfil", methods=["POST", "GET"])
def perfil():
	add_funcionario = funcionario_form()
	editar_user = EditarUserForm()

	if editar_user.validate_on_submit(): 
		bcript = Bcrypt()		
		current_user.nome = editar_user.nome.data
		current_user.username = editar_user.username.data
		current_user.email = editar_user.email.data
		current_user.data_nasc = editar_user.data_nascimento.data

		current_user.hhash = bcript.generate_password_hash(editar_user.senha.data)

		current_user.avatar = adicionar_avatar(editar_user.foto.data, editar_user.username.data) 
		db.session.commit()

		flash("Dados atualizados!","success")

	return render_template("perfil.html", add_funcionario=add_funcionario, editar_user=editar_user)

administer/administer/templates/base.html
<!doctype html>
<!--
  Material Design Lite
  Copyright 2015 Google Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License
-->
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Administer System</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="{{url_for('static', filename='img/dashboard/android-desktop.png')}}">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="{{url_for('static', filename='img/dashboard/ios-desktop.png')}}">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

    <link rel="shortcut icon" href="{{url_for('static', filename='img/dashboard/favicon.png')}}
    ">

    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->

    <!-- Links via CDN do MDBootstrap -->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet">

    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/js/mdb.min.js"></script>

    <!--Links CDN para MDLite-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    <!--link CDN Semantic UI -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>


    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.cyan-light_blue.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles_dashboard.css')}}">

    <!--link para o AJAX -->
	  <meta http-equiv="cache-control" content="max-age=0" />
	  <meta http-equiv="cache-control" content="no-cache" />
	  <meta http-equiv="expires" content="Tue, 01 Jan 2030 1:00:00 GMT" />
	  <meta http-equiv="pragma" content="no-cache" />
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    
    <style>

    #view-source {
      position: fixed;
      display: block;
      right: 0;
      bottom: 0;
      margin-right: 40px;
      margin-bottom: 40px;
      z-index: 900;
    }
    </style>
  </head>
  <body>

    <!--Modal de adicionar funcionário-->
    <div class="modal fade" id="modalSubscriptionForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold">Adicionar Funcionário</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <form action="{{url_for('funcionarios.adicionar')}}" method="POST">
            {{ add_funcionario.hidden_tag()}}
            <div class="modal-body mx-3">

              <div class="md-form mb-5">
                <i class="fas fa-user prefix grey-text"></i>
                {{ add_funcionario.nome(type="text", id="form3", class="form-control validate", placeholder="Nome") }}
              </div>

              <div class="md-form mb-4">
                <i class="fas fa-envelope prefix grey-text"></i>
                {{ add_funcionario.email(class="form-control validate", placeholder="E-mail") }}
              </div>

              <div class="md-form mb-4">
                <i class="fas fa-user-clock prefix grey-text"></i>
                {{ add_funcionario.idade(type="number",class="form-control validate", placeholder="Idade") }}
              </div>

              <div class="md-form mb-4">
                <i class="fas fa-puzzle-piece prefix grey-text"></i>
                <label data-error="wrong" data-success="right" for="form0">Cargo</label>
                <br/><br>     
                {{ add_funcionario.setor(class="browser-default custom-select") }}
              </div>

            </div>
            <div class="modal-footer d-flex justify-content-center">
                {{ add_funcionario.submit(class="btn btn-indigo") }}
              <i class="fas fa-paper-plane-o ml-1"></i>
            </div>
          </form>
        </div>
      </div>
    </div>


    <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
      <header class="demo-header mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600">
        <div class="mdl-layout__header-row">
          <span style="float: left" class="mdl-layout-title">{%block title%} {% endblock %}</span>
          <div class="mdl-layout-spacer">
          </div>
        </div>
      </header>
      <div class="demo-drawer mdl-layout__drawer mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
        <header class="demo-drawer-header">
          <img src="{{url_for('static', filename='img/avatares/'+current_user.avatar)}}" class="demo-avatar">
          <div class="demo-avatar-dropdown">
            <span>{{current_user.username}}</span>
            <div class="mdl-layout-spacer"></div>
            <button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
              <i class="material-icons" role="presentation">arrow_drop_down</i>
              <span class="visuallyhidden">Accounts</span>
            </button>
            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="accbtn">
              <a href="{{url_for('usuarios.perfil')}}"> <li class="mdl-menu__item"><i class="material-icons">account_box</i>Ver perfil</li></a>
            </ul>
          </div>
        </header>
        <nav class="demo-navigation mdl-navigation mdl-color--blue-grey-800">
          <a  class="mdl-navigation__link" href="{{url_for('usuarios.dashboard')}}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">home</i>Home</a>
          <a data-toggle="modal" data-target="#modalSubscriptionForm" class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation" >add</i>Novo Funcionário</a>
          <a class="mdl-navigation__link" href="{{url_for('funcionarios.meus_funcionarios')}}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">list</i>Meus Funcionários</a>
          <a class="mdl-navigation__link" href="{{url_for('funcionarios.exibe_all')}}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">list</i>Todos Funcionários</a>
          <a class="mdl-navigation__link" href="{{url_for('usuarios.logout')}}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">report</i>Sair</a>
        </nav>
      </div>
    </div>


    <!--
    <div class="text-center">
      <a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalSubscriptionForm">Launch
        Modal Subscription Form</a>
    </div>
    -->
    
    <div style="padding-top: 50px" class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
      <main style="padding-top: 20px" class="mdl-layout__content mdl-color--grey-100">
        <div class="mdl-grid demo-content text-center">
          
            <!--Notificações-->
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="col-md-12 col-sm-12 col-12">
                  <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}

            <!--Conteudo do sistema-->
            {%block content%} 

            {% endblock %}

         
        </div>
        <div>
          {%  block pagination %}

          {% endblock %}
        </div>
      </main>
    </div>

    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script type="text/javascript" src="{{url_for('static',filename='js/style.js')}}"></script>
  </body>
</html>

administer/administer/templates/home.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Iniciar - Administer</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{{url_for('static',filename='css/bootstrap.min.css')}}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{{url_for('static',filename='css/mdb.min.css')}}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{{url_for('static',filename='css/style.css')}}" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark black">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('principal.index') }}"><strong>Administer</strong></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        </nav>

        <div class="view intro-2">
            <div class="full-bg-img">
                <div class="mask rgba-black-strong flex-center">
                <div class="container">
                    <div class="white-text text-center wow fadeInUp">
                    <h2>This is ADMINISTER</h2>
                    <h5>Gerência diversos usuários com a palma da mão!</h5>
                    <br>
                    <p>
                        Com o crescer das instituições, o número de usuários de um dado sistema,
                        tende a aumentar de maneira continua e gerênciar os mesmos sem uma ferramenta
                        fácil e prática, não é uma tafera boa. Dito isso, a UFMG Informática Jr, desenvolveu
                        esse sistema web capaz de gerênciar todo esse fluxo de informação. Trazendo melhor 
                        produtividade e experiência para nossos clientes.
                    </p>
                    <br><br>
                    <h3>Acesse sua conta agora</h3>
                    <div class="text-center">
                        <a href="" class="btn btn-info btn-rounded mb-4" data-toggle="modal" data-target="#modalLoginForm">
                            Entrar
                        </a>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
        <!-- First Content -->
    
    </header>
    <!--Main Navigation-->

    
    <!--Main Layout-->
    <main class="text-center" style="margin-top: 50px; margin-bottom: 50px;">
    
        <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% for mess in get_flashed_messages() %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <button type="button" class="fade close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{ mess }}
                    </div>
                {% endfor %}
                
                <!--Conteudo-->
                <h2>Não é cadastrado? Cadastre-se agora!</h2><br>
                <form action="{{url_for('usuarios.adicionar')}}" class="border border-light p-5" method="POST" enctype="multipart/form-data">
                    {{ form_add.hidden_tag()}}
                    
                    <p class="h4 mb-4 text-center">Preencher dados</p>
                    
                    {{ form_add.nome(class="form-control mb-4", placeholder="Nome") }}
                    {{ form_add.email(class="form-control mb-4", placeholder="Email", type="email") }}
                    {{ form_add.username(class="form-control mb-4", placeholder="Nome de usuario") }}
                    {{ form_add.data_nascimento(class="form-control mb-4", placeholder="Data de nascimento", type="date") }}
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                        </div>
                        <div class="custom-file">
                            {{ form_add.foto(class="custom-file-input", id="inputGroupFile01") }}
                            <label class="custom-file-label" for="inputGroupFile01">Escolha uma foto</label>
                        </div>
                    </div><br>
                    {{ form_add.senha(class="form-control mb-4", placeholder="Senha") }}
                    {{ form_add.conf_senha(class="form-control mb-4", placeholder="Confirmar senha") }}
                    {{ form_add.submit(class="btn btn-info btn-block my-4") }}                      
                </form>
    
            </div>
        </div>
        </div>
    
    </main>
    <!--Main Layout-->

    <div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Entrar na conta</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{url_for('usuarios.login')}}" method="POST">
                <div class="modal-body mx-3">
                    
                    {{ form_login.hidden_tag() }}
                    <div class="md-form mb-5">
                    <i class="fas fa-envelope prefix grey-text"></i>
                    {{ form_login.email(type="email",id="defaultForm-email",class="form-control validate") }}
                    <label data-error="wrong" data-success="right" for="defaultForm-email">Seu email</label>
                    </div>

                    <div class="md-form mb-4">
                    <i class="fas fa-lock prefix grey-text"></i>
                    {{ form_login.senha(type="password", id="defaultForm-pass", class="form-control validate") }}
                    <label data-error="wrong" data-success="right" for="defaultForm-pass">Sua senha</label>
                    </div>

                    <div class="custom-control custom-checkbox">
                        {{ form_login.lembrar(type="checkbox", class="custom-control-input", id="defaultUnchecked")}}
                        <label class="custom-control-label" for="defaultUnchecked">Lembrar-me</label>
                    </div>
                </div>
                <div class="modal-footer d-flex justify-content-center">
                {{ form_login.submit(class="btn btn-info") }}
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <footer class="page-footer font-small black">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2018 Copyright:
          <a href="https://www.facebook.com/ufmginformaticajr/"> Administer</a>
        </div>
        <!-- Copyright -->
      
    </footer>
    <!-- Footer -->

    <script type="text/javascript" src="{{url_for('static',filename='js/jquery-3.3.1.min.js')}}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{{url_for('static',filename='js/popper.min.js')}}"></script>
    <script type="text/javascript">
        $(function () {
        $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{{url_for('static',filename='js/bootstrap.min.js')}}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{{url_for('static',filename='js/mdb.js')}}"></script>

</body>
</html>